INFO: -N -a -A -D vivid -P -B -T vivid python-cryptography_0.8-1ubuntu2.dsc
Using the following defaults:
name: Ubuntu Archive
email: archive@ubuntu.com
Checking: python-cryptography_0.8-1ubuntu2.dsc
Mode: archive

Retrieving madison output:      pass
Distribution:                   pass
Pocket:                         pass
Maintainer:                     SKIP (archive)
Changed-By:                     SKIP (archive)
Source has orig.tar.gz:         pass
Recent date:                    SKIP (archive)
Output of diffstat:             SKIP (could not find debdiff or diff.*)
Vcs files in diffstat:          No such file or directory
pass
Vcs files in patch files:       SKIP: could not find 'python-cryptography_0.8-1ubuntu2.debdiff'
Version:                        SKIP (initial release?)
Newest version:                 FAIL
 Current: 0.8-1ubuntu2
 Found:   0.8-1ubuntu2
Diff chaff:                     pass
Merged changelog:               pass
Changelog autocloses LP bugs:   pass
Patch system:                   SKIP: (diff not specified)
Patch tagging:                  SKIP: (diff not specified)
Check bashisms in 'debian':     pass
Reverse Debdiff:                SKIP: could not find 'python-cryptography_0.8-1ubuntu2.debdiff'
Bad files:                      pass
Vcs files in source:            pass
Ubuntu archive:
  python-cryptography | 0.8-1ubuntu2 | vivid/universe  | source, amd64, arm64, armhf, i386, powerpc, ppc64el
Debian archive:
  python-cryptography | 0.8-1   | experimental | source, amd64, arm64, armel, armhf, i386, kfreebsd-amd64, kfreebsd-i386, mips, mipsel, powerpc, ppc64el, s390x, sparc

Has debian/watch:               pass
Output of lintian:              
 W: python-cryptography source: newer-standards-version 3.9.6 (current is 3.9.5)

Output of licensecheck:         
 Unique licenses:
  UNKNOWN

 Full output:
  src/cryptography/__about__.py: UNKNOWN

Output of suspicious-source:    
 ./debian/upstream/signing-key.asc:                PGP public key block

Check bashisms in '.':          pass (skipped ./configure and ./config.guess)
chmod/chown in debian/:         pass
bash network redirections:      pass
/bin/sh as shell in debian/:    pass
Upstream source:                https://cryptography.io/
Source build:                    dpkg-buildpackage -rfakeroot -d -us -uc -S
dpkg-buildpackage: source package python-cryptography
dpkg-buildpackage: source version 0.8-1ubuntu2
dpkg-buildpackage: source distribution vivid
dpkg-buildpackage: source changed by Matthias Klose <doko@ubuntu.com>
 dpkg-source --before-build source_build
 fakeroot debian/rules clean
dh clean --with python2,python3 --buildsystem=pybuild
   dh_testdir -O--buildsystem=pybuild
   debian/rules override_dh_auto_clean
make[1]: Entering directory `/home/sarnold/ubuntu/security/audits/python-cryptography/vivid/source/tmp.VwI4SHDTQY/source_build'
dh_auto_clean
I: pybuild base:170: python2.7 setup.py clean 
running clean
removing '/home/sarnold/ubuntu/security/audits/python-cryptography/vivid/source/tmp.VwI4SHDTQY/source_build/.pybuild/pythonX.Y_2.7/build' (and everything under it)
'build/bdist.linux-x86_64' does not exist -- can't clean it
'build/scripts-2.7' does not exist -- can't clean it
I: pybuild base:170: python3.4 setup.py clean 
Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    from setuptools import find_packages, setup
ImportError: No module named 'setuptools'
E: pybuild pybuild:256: clean: plugin distutils failed with: exit code=1: python3.4 setup.py clean 
dh_auto_clean: pybuild --clean -i python{version} -p 3.4 --dir . returned exit code 13
make[1]: *** [override_dh_auto_clean] Error 13
make[1]: Leaving directory `/home/sarnold/ubuntu/security/audits/python-cryptography/vivid/source/tmp.VwI4SHDTQY/source_build'
make: *** [clean] Error 2
dpkg-buildpackage: error: fakeroot debian/rules clean gave error exit status 2
debuild: fatal error at line 1364:
dpkg-buildpackage -rfakeroot -d -us -uc -S failed
FAIL

Statistics:
 Size (unpacked): 3M
 Number files: 248
 Number directories: 42
 Number symlinks: 0
 Estimated lines of source: 29816
Check existing binaries (may take a while): 
 found existing: python-cryptography vivid/universe
 found existing: python3-cryptography vivid/universe
 found existing: python-cryptography-doc vivid/universe
 Total: 3 (new=0, existing=3)
------
FAILED
