Candidate: CVE-2017-18342
PublicDate: 2017-12-31
References:
 https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-18342
 https://github.com/yaml/pyyaml/pull/74
Description:
 (In PyYAML before 4.1, the yaml.load() API could execute arbitrary code.
 ...)
Ubuntu-Description:
Notes:
 sarnold> The patch changes the incredibly-unsafe yaml.load to the
  behaviour of safe_load; despite being many years overdue, it's also
  likely to break something.
Bugs:
 http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=902878
Priority: medium
Discovered-by:
Assigned-to:


Patches_pyyaml:
upstream_pyyaml: needed
precise/esm_pyyaml: needed
trusty_pyyaml: needed
xenial_pyyaml: needed
bionic_pyyaml: needed
cosmic_pyyaml: needed
devel_pyyaml: needed
