Candidate: CVE-2020-14422
PublicDate: 2020-06-18 14:15:00 UTC
References:
 https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-14422
 https://github.com/python/cpython/pull/20956
Description:
 Lib/ipaddress.py in Python through 3.8.3 improperly computes hash values in
 the IPv4Interface and IPv6Interface classes, which might allow a remote
 attacker to cause a denial of service if an application is affected by the
 performance of a dictionary containing IPv4Interface or IPv6Interface
 objects, and this attacker can cause many dictionary entries to be created.
Ubuntu-Description:
Notes:
 mdeslaur> as of 2020-06-23, fix not commited upstream
Mitigation:
Bugs:
 https://bugs.python.org/issue41004
Priority: low
Discovered-by:
Assigned-to:
CVSS:
 nvd: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H


Patches_python3.8:
upstream_python3.8: needs-triage
precise/esm_python3.8: DNE
trusty_python3.8: ignored (out of standard support)
trusty/esm_python3.8: DNE
xenial_python3.8: DNE
bionic_python3.8: needs-triage
eoan_python3.8: needs-triage
focal_python3.8: needs-triage
devel_python3.8: needs-triage

Patches_python3.7:
upstream_python3.7: needs-triage
precise/esm_python3.7: DNE
trusty_python3.7: ignored (out of standard support)
trusty/esm_python3.7: DNE
xenial_python3.7: DNE
bionic_python3.7: needs-triage
eoan_python3.7: needs-triage
focal_python3.7: DNE
devel_python3.7: DNE

Patches_python3.5:
upstream_python3.5: needs-triage
precise/esm_python3.5: DNE
trusty_python3.5: ignored (out of standard support)
trusty/esm_python3.5: needs-triage
xenial_python3.5: needs-triage
bionic_python3.5: DNE
eoan_python3.5: DNE
focal_python3.5: DNE
devel_python3.5: DNE

Patches_python3.4:
upstream_python3.4: needs-triage
precise/esm_python3.4: DNE
trusty_python3.4: ignored (out of standard support)
trusty/esm_python3.4: needs-triage
xenial_python3.4: DNE
bionic_python3.4: DNE
eoan_python3.4: DNE
focal_python3.4: DNE
devel_python3.4: DNE
