Candidate: CVE-2018-1000808
PublicDate: 2018-10-08
References:
 https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-1000808
Description:
 Python Cryptographic Authority pyopenssl version Before 17.5.0 contains a
 CWE - 401 : Failure to Release Memory Before Removing Last Reference
 vulnerability in PKCS #12 Store that can result in Denial of service if
 memory runs low or is exhausted. This attack appear to be exploitable via
 Depends upon calling application, however it could be as simple as
 initiating a TLS connection. Anything that would cause the calling
 application to reload certificates from a PKCS #12 store.. This
 vulnerability appears to have been fixed in 17.5.0.
Ubuntu-Description:
Notes:
 mdeslaur> requires python-cryptography 2.1.4 which adds X509_up_ref, see
 mdeslaur> https://github.com/pyca/cryptography/pull/4028
Bugs:
Priority: medium
Discovered-by:
Assigned-to: mdeslaur


Patches_pyopenssl:
 upstream: https://github.com/pyca/pyopenssl/pull/723
 upstream: https://github.com/pyca/pyopenssl/commit/e73818600065821d588af475b024f4eb518c3509
upstream_pyopenssl: released (17.5.0)
precise/esm_pyopenssl: needs-triage
trusty_pyopenssl: not-affected (code not present)
xenial_pyopenssl: needed
bionic_pyopenssl: not-affected (17.5.0-1)
devel_pyopenssl: not-affected (17.5.0-1)
