Candidate: CVE-2012-3444
PublicDate: 2012-07-31
References:
 http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2012-3444
 https://www.djangoproject.com/weblog/2012/jul/30/security-releases-issued/
 http://www.openwall.com/lists/oss-security/2012/07/31/1
 http://www.openwall.com/lists/oss-security/2012/07/31/2
Description:
 The get_image_dimensions function in the image-handling functionality in
 Django before 1.3.2 and 1.4.x before 1.4.1 uses a constant chunk size in
 all attempts to determine dimensions, which allows remote attackers to
 cause a denial of service (process or thread consumption) via a large TIFF
 image.
Ubuntu-Description:
Notes:
 mdeslaur> possible regression, see LP: #1031733
Bugs:
 http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=683364
 https://bugs.launchpad.net/ubuntu/+source/python-django/+bug/1031733
Priority: medium
Discovered-by:
Assigned-to:

Patches_python-django:
 vendor: http://www.debian.org/security/2012/dsa-2529
upstream_python-django: released (1.3.2,1.4.1)
hardy_python-django: ignored (reached end-of-life)
lucid_python-django: needed
natty_python-django: needed
oneiric_python-django: needed
precise_python-django: needed
devel_python-django: not-affected (1.4.1-1)
