Candidate: CVE-2019-19911
PublicDate: 2020-01-05 22:15:00 UTC
References:
 https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-19911
 https://github.com/python-pillow/Pillow/commit/774e53bb132461d8d5ebefec1162e29ec0ebc63d (6.2.2)
 https://pillow.readthedocs.io/en/stable/releasenotes/6.2.2.html
Description:
 There is a DoS vulnerability in Pillow before 6.2.2 caused by
 FpxImagePlugin.py calling the range function on an unvalidated 32-bit
 integer if the number of bands is large. On Windows running 32-bit Python,
 this results in an OverflowError or MemoryError due to the 2 GB limit.
 However, on Linux running 64-bit Python this results in the process being
 terminated by the OOM killer.
Ubuntu-Description:
Notes:
Mitigation:
Bugs:
 http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=948224
Priority: medium
Discovered-by:
Assigned-to:


Patches_pillow:
upstream_pillow: needs-triage
precise/esm_pillow: DNE
trusty_pillow: ignored (out of standard support)
trusty/esm_pillow: needs-triage
xenial_pillow: needs-triage
bionic_pillow: needs-triage
disco_pillow: needs-triage
eoan_pillow: needs-triage
devel_pillow: needs-triage
